# welcome to numpy 

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,5,8,6,4,8,9,6,5]])

In [3]:
myarr[0,1]

5

In [4]:
myarr.shape


(1, 9)

In [5]:
myarr.dtype


dtype('int32')

In [6]:
myarr[0,1] = 45

In [7]:
myarr

array([[ 3, 45,  8,  6,  4,  8,  9,  6,  5]])

## array banana 

In [10]:
listarray = np.array([[1,2,3],[5,6,7],[8,9,0]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 0]])

In [12]:
zeros = np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
lspace = np.linspace(1,4,4)

In [23]:
lspace

array([1., 2., 3., 4.])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[3.3e-322, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000],
       [0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000]])

In [27]:
emp_like = np.empty_like(lspace)

In [29]:
emp_like

array([1., 2., 3., 4.])

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr = arr.reshape(3,33)

In [35]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [39]:
ar  = np.array(x)

In [40]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
ar.sum(axis=0)

array([12, 15, 18])

In [42]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [43]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [44]:
ar.flat


In [49]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [50]:
ar.ndim


2

In [51]:
ar.size

9

In [52]:
ar.nbytes

36

In [54]:
on = np.array([1,20,68,4,64,35,41,65,4,35,4,3,5,14,64,35,45,50])

In [55]:
on.argmax()

2

In [56]:
on.argmin()

0

In [58]:
on.argsort()

array([ 0, 11, 10,  8,  3, 12, 13,  1,  5,  9, 15,  6, 16, 17,  4, 14,  7,
        2], dtype=int64)

In [59]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
ar2 = np.array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [61]:
ar2

array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [62]:
ar + ar2

array([[ 8,  6,  4],
       [12, 10,  8],
       [16, 14, 12]])

In [63]:
ar * ar2


array([[ 7,  8,  3],
       [32, 25, 12],
       [63, 48, 27]])

In [66]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [67]:
ar.sum()

45

In [68]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
np.where(ar>7)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [71]:
np.count_nonzero(ar)

9